/*
 * @Author: victorika
 * @Date: 2025-01-20 14:29:26
 * @Last Modified by: victorika
 * @Last Modified time: 2025-01-20 14:39:51
 */
#pragma once

#include <cstddef>
#include <cstdint>
#include <vector>
#include "status.h"

namespace jitfusion {

/// \brief Simple arena allocator.
///
/// Memory is allocated from system in units of chunk-size, and dished out in the
/// requested sizes. If the requested size > chunk-size, allocate directly from the
/// system.
///
/// The allocated memory gets released only when the arena is destroyed, or on
/// Reset.
///
/// This code is not multi-thread safe, and avoids all locking for efficiency.
///
class Arena {
 public:
  // Default alignment for allocations. 8 bytes is enough for all scalar types
  // used in JitFusion (including double/int64) and for StringStruct/ListStruct
  // data pointers that may be accessed via vector load/store.
  static constexpr size_t kDefaultAlignment = 8;

  explicit Arena(size_t min_chunk_size = 4096) : min_chunk_size_(min_chunk_size) {};
  ~Arena() { ReleaseChunks(false); }
  // Allocate buffer of requested size with the given alignment.
  // `size == 0` is a valid no-op and returns nullptr; callers treating an
  // empty buffer (empty list/string) as legal data rely on this. The
  // returned null pointer must NOT be dereferenced.
  // `alignment` must be a power of two. Default alignment is 8 bytes, which
  // satisfies alignof(double)/alignof(int64_t) and is safe for SIMD accesses
  // generated by LLVM's auto-vectorizer on list payloads.
  uint8_t* Allocate(size_t size, size_t alignment = kDefaultAlignment);

  // Reset arena state.
  void Reset();

  // total bytes allocated from system.
  [[nodiscard]] size_t total_bytes() const { return total_bytes_; }

  // total bytes available for allocations.
  [[nodiscard]] size_t avail_bytes() const { return avail_bytes_; }

 private:
  struct Chunk {
    Chunk(uint8_t* buf, size_t size) : buf_(buf), size_(size) {}

    uint8_t* buf_;
    size_t size_;
  };

  static Status Allocate(uint8_t** buf, size_t size);

  static void Free(uint8_t* buf);

  // Allocate new chunk.
  Status AllocateChunk(size_t size);

  // release memory from buffers.
  void ReleaseChunks(bool retain_first);

  // The chunk-size used for allocations from system.
  size_t min_chunk_size_;

  // Total bytes allocated from system.
  size_t total_bytes_{};

  // Bytes available from allocated chunk.
  size_t avail_bytes_{};

  // buffer from current chunk.
  uint8_t* avail_buf_{};

  // List of allocated chunks.
  std::vector<Chunk> chunks_;
};

}  // namespace jitfusion