/*
 * @Author: victorika
 * @Date: 2025-01-20 14:29:26
 * @Last Modified by: victorika
 * @Last Modified time: 2026-05-11 14:56:47
 */
#pragma once

#include <cstddef>
#include <cstdint>
#include <new>
#include <type_traits>
#include <utility>
#include <vector>
#include "status.h"

namespace jitfusion {

/// \brief Simple arena allocator.
///
/// Memory is allocated from system in units of chunk-size, and dished out in the
/// requested sizes. If the requested size > chunk-size, allocate directly from the
/// system.
///
/// The allocated memory gets released only when the arena is destroyed, or on
/// Reset.
///
/// In addition to raw byte allocation, Arena can also construct typed objects
/// via Create<T>(...). Non-trivially-destructible objects so created have
/// their destructors run automatically on Reset() / ~Arena() (in reverse
/// construction order, mirroring C++ stack semantics). This lets callers
/// place objects holding heap-allocated state — std::unordered_map,
/// std::vector, std::string, etc. — directly on the arena without leaking
/// the heap allocations those objects internally own.
///
/// This code is not multi-thread safe, and avoids all locking for efficiency.
///
class Arena {
 public:
  // Default alignment for allocations. 8 bytes is enough for all scalar types
  // used in JitFusion (including double/int64) and for StringStruct/ListStruct
  // data pointers that may be accessed via vector load/store.
  static constexpr size_t kDefaultAlignment = 8;

  explicit Arena(size_t min_chunk_size = 4096) : min_chunk_size_(min_chunk_size) {};
  ~Arena() {
    RunFinalizers();
    ReleaseChunks(false);
  }
  // Allocate buffer of requested size with the given alignment.
  // `size == 0` is a valid no-op and returns nullptr; callers treating an
  // empty buffer (empty list/string) as legal data rely on this. The
  // returned null pointer must NOT be dereferenced.
  // `alignment` must be a power of two. Default alignment is 8 bytes, which
  // satisfies alignof(double)/alignof(int64_t) and is safe for SIMD accesses
  // generated by LLVM's auto-vectorizer on list payloads.
  uint8_t* Allocate(size_t size, size_t alignment = kDefaultAlignment);

  // Construct a `T` in arena-owned storage and return a pointer to it.
  //
  // Storage for the object itself is bump-allocated from the arena (so the
  // object survives until the next Reset() / ~Arena), and — if T has a
  // non-trivial destructor — a finalizer record is pushed onto an internal
  // vector so that ~T() runs when the arena is reset or destroyed.
  //
  // Destruction order is the reverse of construction order, matching C++
  // stack semantics. This matters when later-constructed objects observe
  // earlier-constructed ones (e.g. an object holding a non-owning pointer
  // into another arena-resident object): ~T() of the later object runs
  // first, while the earlier object is still alive.
  //
  // Returns nullptr if the underlying chunk allocation for T's storage
  // fails. The finalizer vector itself uses heap allocation; if that
  // allocation throws std::bad_alloc, the exception propagates out (this
  // is the standard library's reporting channel for OOM in vector growth
  // and matches how every other heap-backed container in the codebase
  // behaves).
  //
  // Trivial-destructor types skip the finalizer record entirely — there is
  // zero per-call overhead beyond the bump allocation.
  template <typename T, typename... Args>
  T* Create(Args&&... args) {
    void* mem = Allocate(sizeof(T), alignof(T));
    if (mem == nullptr) {
      return nullptr;
    }
    T* obj = ::new (mem) T(std::forward<Args>(args)...);
    if constexpr (!std::is_trivially_destructible_v<T>) {
      finalizers_.emplace_back(obj, &DestroyImpl<T>);
    }
    return obj;
  }

  // Reset arena state.
  void Reset();

  // total bytes allocated from system.
  [[nodiscard]] size_t total_bytes() const { return total_bytes_; }

  // total bytes available for allocations.
  [[nodiscard]] size_t avail_bytes() const { return avail_bytes_; }

 private:
  struct Chunk {
    Chunk(uint8_t* buf, size_t size) : buf_(buf), size_(size) {}

    uint8_t* buf_;
    size_t size_;
  };

  // Type-erased finalizer record. Stored in a vector so destruction can
  // walk it in reverse for LIFO order, mirroring C++ stack semantics.
  // The vector's heap buffer survives across Reset() (clear() preserves
  // capacity), so steady-state Execute calls register finalizers without
  // triggering further heap traffic once the working set is reached.
  using FinalizerFn = void (*)(void*) noexcept;
  struct Finalizer {
    Finalizer() = default;
    Finalizer(void* obj, FinalizerFn fn) : obj(obj), fn(fn) {}
    void* obj;
    FinalizerFn fn;
  };

  static Status Allocate(uint8_t** buf, size_t size);

  static void Free(uint8_t* buf);

  // Allocate new chunk.
  Status AllocateChunk(size_t size);

  // release memory from buffers.
  void ReleaseChunks(bool retain_first);

  // Walk the finalizer vector in reverse and invoke each ~T(), then
  // clear() the vector. clear() preserves capacity so the next batch of
  // registrations reuses the buffer.
  void RunFinalizers() noexcept;

  template <typename T>
  static void DestroyImpl(void* p) noexcept {
    static_cast<T*>(p)->~T();
  }

  // The chunk-size used for allocations from system.
  size_t min_chunk_size_;

  // Total bytes allocated from system.
  size_t total_bytes_{};

  // Bytes available from allocated chunk.
  size_t avail_bytes_{};

  // buffer from current chunk.
  uint8_t* avail_buf_{};

  // List of allocated chunks.
  std::vector<Chunk> chunks_;

  // Finalizer records in registration order. Walked in reverse on
  // RunFinalizers() to produce LIFO destruction.
  std::vector<Finalizer> finalizers_;
};

}  // namespace jitfusion